export const weaponTypeInfo = new Map<string, { type: string, as: number }>([
  ["Glove", {"type":"Glove","as":0.63}],
  ["Tonfa", {"type":"Tonfa","as":0.5}],
  ["Bat", {"type":"Bat","as":0.56}],
  ["Hammer", {"type":"Hammer","as":0.455}],
  ["Whip", {"type":"Whip","as":0.55}],
  ["HighAngleFire", {"type":"HighAngleFire","as":0.51}],
  ["DirectFire", {"type":"DirectFire","as":0.55}],
  ["Bow", {"type":"Bow","as":0.65}],
  ["CrossBow", {"type":"CrossBow","as":0.54}],
  ["Pistol", {"type":"Pistol","as":0.505}],
  ["AssaultRifle", {"type":"AssaultRifle","as":0.55}],
  ["SniperRifle", {"type":"SniperRifle","as":0.43}],
  ["Axe", {"type":"Axe","as":0.485}],
  ["OneHandSword", {"type":"OneHandSword","as":0.58}],
  ["TwoHandSword", {"type":"TwoHandSword","as":0.56}],
  ["DualSword", {"type":"DualSword","as":0.43}],
  ["Spear", {"type":"Spear","as":0.445}],
  ["Nunchaku", {"type":"Nunchaku","as":0.56}],
  ["Rapier", {"type":"Rapier","as":0.615}],
  ["Guitar", {"type":"Guitar","as":0.495}],
  ["Camera", {"type":"Camera","as":0.55}],
  ["Arcana", {"type":"Arcana","as":0.555}],
  ["VFArm", {"type":"VFArm","as":0.5}]
]);